Component/dashboard
kodiraonica/FE_modul_2024_recepti pull request #3
Opened 2024-02-15 19:13 UTC by M-Lucan

2024-02-22 15:02 UTC, tonkec requested changes

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    background-color: var(--bgcolor);
zasto svi elementi imaju istu boju? Vjerojatno ces to prebrisat kasnije

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    justify-content: center;
pogledaj koja je razlika izmedu justify-content i justifty-items.

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    box-sizing: border-box;
vec si stavio gore na sve elemente box-sizing: border-box

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    flex-wrap: wrap;
vec si stavio wrap sa flex-flow, zar ne?

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    justify-content: left;
ne postoji left

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    width: 295px;
zasto magicni broj?

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    flex-direction: row;
mislim da je po defaultu row

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    justify-content: flex-start;
mislim da je default `flex-start` zar ne

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    align-content: flex-end;
koja je razlika izmedu align-content i align-items?

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    flex-wrap: nowrap;
isto default, dakle ne treba ti ova linija

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    display: flex;
ajmo ne stavljat tipografske elemente u layout alogritme.

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    width: 250px;
magic number

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    flex-wrap: nowrap;
ne treba ti

2024-02-22 15:02 UTC, tonkec commented on recepti.css
> +    width: 100%;
defaultno je 100%?

2024-02-22 15:02 UTC, tonkec commented on recepti.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,800;1,600&display=swap" rel="stylesheet">
font family link uvijek ide prije css linka

2024-02-26 13:54 UTC, M-Lucan commented on recepti.css
> +    width: 295px;
Stavljao sam te "magične brojeve" kako bi stranica bila što sličnija onoj koju si nam dala za primjer.

2024-02-26 13:56 UTC, M-Lucan commented on recepti.css
> +    align-content: flex-end;
Često mi je ostalo tako jer si preko inspect elementa namjestim flex da mi izgleda kako hoću, pa mi ostane višak kad kopiram.

2024-02-26 14:09 UTC, M-Lucan commented
Ispravljeno, molim provjeriti.

2024-03-06 06:20 UTC, tonkec approved these changes

2024-03-06 06:20 UTC, merged